# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='raj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=20)),
                ('rollno', models.CharField(max_length=10)),
            ],
        ),
    ]
