# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_raj'),
    ]

    operations = [
        migrations.CreateModel(
            name='choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shurt_size', models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large')], max_length=1)),
            ],
        ),
    ]
