# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='profit',
            fields=[
                ('rno', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('branch', models.CharField(choices=[('cse', 'cse'), ('ece', 'ece'), ('eee', 'eee'), ('mec', 'mec')], max_length=3)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
